name: bloc_ecommerce
description: "A ecommerce app using bloc state management & firebase backend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.0
  meta: ^1.11.0
  social_login_buttons: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
